sudo:
  false

language:
  node_js

node_js:
  - 8

script:
  - npm run test

after_script:
  - npm run coveralls

deploy:
  provider: npm
  email: eskarev@gmail.com
  skip_cleanup: true
  on:
    tags: true
    branch: master
  api_key:
    secure: Tz+IGyPr8mMj3btajVZWvaI9DgQev/efCUGVDomz+tHiH/HVZ0TVNFLMWCh79Nc/jedF6Z/oD1uaarqOkSXaiXHri+pzRAzL3PmBxpjeBjJzmxEYr4/amcpOqDbiy+rhcvRXDSwXEbuGz9+Ikh7Ijw33xeEF56yJEZrYricr09Ob6q17xP/z+fFDKyTNenBQ2P1eexJ3AF/9XbZiBlwj4TrzF6HTCFHIjfg7UnqGWfuxvWmHk36nvBPFbibcPlThjZnGHrrceNwtd+7SAHvkQccXNrjDEww2Lz0GEloA80zvidftgKdid2fGUsQRm6uPZ8wkNS2Xekn3/WyBHOOiokIrI3jjxfw1z0pxXAHiWGvsqdPTy93u0fGlQZ3xcX5QeDjtrT0SGarmpKxmQbrH2xai3V3c4WReMLxihXRuu5R5WfXoAodioP/Mzc0x+6DIB1yFgafkVdJ3tnGUAYssp/mKdu+Da8392Cmy0nBU+nRf4jmaKBKIzphpuPHR8pzwWOW0k9Y6rmovJwOwk/tPTdZKMBVPak4269ImwA23UFSjnNPYK+VKHhFszcejgqPTOTUDDl0mphP05utEKRUwFxTgC51VpxEERd+qbFFa6zaOu3PDg9tFfovVnNEWTOTJ+DhMTW9LEhpdhWODlq2cig1LTUoEO1Ryuac94gFNGfo=
